# Generated by Django 2.0.13 on 2019-07-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190717_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
