# Generated by Django 2.0.13 on 2019-07-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tgid',
        ),
    ]
