# Generated by Django 2.0.13 on 2019-07-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_order_tgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dops',
            field=models.CharField(max_length=200),
        ),
    ]
